from setuptools import setup


def main():
    setup(
        name="me22b214_mlopslib",
        version="0.1.50",
        author="ns64",
        author_email="yashpurswani4@gmail.com",
        packages=[
            "me22b214_mlopslib",
            "me22b214_mlopslib.clusterings",
            "me22b214_mlopslib.features",
            "me22b214_mlopslib.features._research_only",
            "me22b214_mlopslib.features.gim",
            "me22b214_mlopslib.features.lightglue",
            "me22b214_mlopslib.global_descriptors",
            "me22b214_mlopslib.localizers",
            "me22b214_mlopslib.matchers",
            "me22b214_mlopslib.matchers._research_only",
            "me22b214_mlopslib.models",
            "me22b214_mlopslib.models._research_only",
            "me22b214_mlopslib.models._research_only.magicleap",
            "me22b214_mlopslib.models._research_only.silk",
            "me22b214_mlopslib.models._research_only.silk.backbones",
            "me22b214_mlopslib.models._research_only.silk.backbones.abstract",
            "me22b214_mlopslib.models._research_only.silk.backbones.loftr",
            "me22b214_mlopslib.models._research_only.silk.backbones.silk",
            "me22b214_mlopslib.models._research_only.silk.backbones.superpoint",
            "me22b214_mlopslib.models._research_only.silk.backbones.unet",
            "me22b214_mlopslib.models._research_only.silk.config",
            "me22b214_mlopslib.models._research_only.silk.cv",
            "me22b214_mlopslib.models._research_only.silk.losses",
            "me22b214_mlopslib.models._research_only.silk.losses.info_nce",
            "me22b214_mlopslib.models._research_only.silk.matching",
            "me22b214_mlopslib.models._research_only.silk.models",
            "me22b214_mlopslib.models._research_only.silk.transforms",
            "me22b214_mlopslib.models._research_only.silk.transforms.cv",
            "me22b214_mlopslib.models.adamatcher",
            "me22b214_mlopslib.models.adamatcher.adamatcher",
            "me22b214_mlopslib.models.adamatcher.adamatcher.ada_module",
            "me22b214_mlopslib.models.adamatcher.adamatcher.backbone",
            "me22b214_mlopslib.models.adamatcher.adamatcher.utils",
            "me22b214_mlopslib.models.adamatcher.config",
            "me22b214_mlopslib.models.adamatcher.lightning",
            "me22b214_mlopslib.models.adamatcher.utils",
            "me22b214_mlopslib.models.alike",
            "me22b214_mlopslib.models.aliked",
            "me22b214_mlopslib.models.aliked.nets",
            "me22b214_mlopslib.models.aspanformer",
            "me22b214_mlopslib.models.aspanformer.aspanformer",
            "me22b214_mlopslib.models.aspanformer.aspanformer.aspan_module",
            "me22b214_mlopslib.models.aspanformer.aspanformer.backbone",
            "me22b214_mlopslib.models.aspanformer.aspanformer.utils",
            "me22b214_mlopslib.models.aspanformer.config",
            "me22b214_mlopslib.models.aspanformer.utils",
            "me22b214_mlopslib.models.cvnet",
            "me22b214_mlopslib.models.cvnet.core",
            "me22b214_mlopslib.models.cvnet.model",
            "me22b214_mlopslib.models.cvnet.model.base",
            "me22b214_mlopslib.models.dac",
            "me22b214_mlopslib.models.darkfeat",
            "me22b214_mlopslib.models.delf_pytorch",
            "me22b214_mlopslib.models.dinov2_salad",
            "me22b214_mlopslib.models.dinov2_salad.models",
            "me22b214_mlopslib.models.dinov2_salad.models.aggregators",
            "me22b214_mlopslib.models.dinov2_salad.models.backbones",
            "me22b214_mlopslib.models.dinov2_salad.models.dinov2",
            "me22b214_mlopslib.models.dinov2_salad.models.dinov2.hub",
            "me22b214_mlopslib.models.dinov2_salad.models.dinov2.hub.depth",
            "me22b214_mlopslib.models.dinov2_salad.models.dinov2.layers",
            "me22b214_mlopslib.models.dinov2_salad.utils",
            "me22b214_mlopslib.models.dirtorch",
            "me22b214_mlopslib.models.dirtorch.nets",
            "me22b214_mlopslib.models.dirtorch.nets.backbones",
            "me22b214_mlopslib.models.dirtorch.nets.layers",
            "me22b214_mlopslib.models.dirtorch.utils",
            "me22b214_mlopslib.models.dkm",
            "me22b214_mlopslib.models.dkm.models",
            "me22b214_mlopslib.models.dkm.models.model_zoo",
            "me22b214_mlopslib.models.dkm.utils",
            "me22b214_mlopslib.models.doppelgangers",
            "me22b214_mlopslib.models.doppelgangers.datasets",
            "me22b214_mlopslib.models.doppelgangers.models",
            "me22b214_mlopslib.models.doppelgangers.third_party",
            "me22b214_mlopslib.models.doppelgangers.third_party.loftr",
            "me22b214_mlopslib.models.doppelgangers.third_party.loftr.backbone",
            "me22b214_mlopslib.models.doppelgangers.third_party.loftr.loftr_module",
            "me22b214_mlopslib.models.doppelgangers.third_party.loftr.utils",
            "me22b214_mlopslib.models.doppelgangers.utils",
            "me22b214_mlopslib.models.ecotr",
            "me22b214_mlopslib.models.ecotr.config",
            "me22b214_mlopslib.models.ecotr.models",
            "me22b214_mlopslib.models.ecotr.models.base",
            "me22b214_mlopslib.models.ecotr.models.ecotr_modules",
            "me22b214_mlopslib.models.ecotr.models.utils",
            "me22b214_mlopslib.models.ecotr.utils",
            "me22b214_mlopslib.models.edgepoint2",
            "me22b214_mlopslib.models.efficientloftr",
            "me22b214_mlopslib.models.efficientloftr.config",
            "me22b214_mlopslib.models.efficientloftr.loftr",
            "me22b214_mlopslib.models.efficientloftr.loftr.backbone",
            "me22b214_mlopslib.models.efficientloftr.loftr.loftr_module",
            "me22b214_mlopslib.models.efficientloftr.loftr.utils",
            "me22b214_mlopslib.models.featurebooster",
            "me22b214_mlopslib.models.fftformer",
            "me22b214_mlopslib.models.fsnet",
            "me22b214_mlopslib.models.fsnet.modules",
            "me22b214_mlopslib.models.gim",
            "me22b214_mlopslib.models.gim.dkm",
            "me22b214_mlopslib.models.gim.dkm.models",
            "me22b214_mlopslib.models.gim.dkm.models.model_zoo",
            "me22b214_mlopslib.models.gim.dkm.utils",
            "me22b214_mlopslib.models.gim.gluefactory",
            "me22b214_mlopslib.models.gim.gluefactory.models",
            "me22b214_mlopslib.models.gim.gluefactory.models.backbones",
            "me22b214_mlopslib.models.gim.gluefactory.models.extractors",
            "me22b214_mlopslib.models.gim.gluefactory.models.matchers",
            "me22b214_mlopslib.models.gim.gluefactory.models.utils",
            "me22b214_mlopslib.models.gim.gluefactory.utils",
            "me22b214_mlopslib.models.gim.loftr",
            "me22b214_mlopslib.models.gim.loftr.backbone",
            "me22b214_mlopslib.models.gim.loftr.configs",
            "me22b214_mlopslib.models.gim.loftr.configs.outdoor",
            "me22b214_mlopslib.models.gim.loftr.submodules",
            "me22b214_mlopslib.models.gim.loftr.utils",
            "me22b214_mlopslib.models.grounded_sam",
            "me22b214_mlopslib.models.isc",
            "me22b214_mlopslib.models.lanet",
            "me22b214_mlopslib.models.lanet.network_v1",
            "me22b214_mlopslib.models.mapfree",
            "me22b214_mlopslib.models.mast3r",
            "me22b214_mlopslib.models.matchformer",
            "me22b214_mlopslib.models.matchformer.backbone",
            "me22b214_mlopslib.models.matchformer.utils",
            "me22b214_mlopslib.models.moge",
            "me22b214_mlopslib.models.mtldesc",
            "me22b214_mlopslib.models.mtldesc.vit",
            "me22b214_mlopslib.models.ncmnet",
            "me22b214_mlopslib.models.omniglue_onnx",
            "me22b214_mlopslib.models.omniglue_onnx.dinov2",
            "me22b214_mlopslib.models.openglue",
            "me22b214_mlopslib.models.openglue.models",
            "me22b214_mlopslib.models.openglue.models.features",
            "me22b214_mlopslib.models.openglue.models.features.opencv",
            "me22b214_mlopslib.models.openglue.models.superglue",
            "me22b214_mlopslib.models.openglue.utils",
            "me22b214_mlopslib.models.panet",
            "me22b214_mlopslib.models.patchnetvlad",
            "me22b214_mlopslib.models.patchnetvlad.models",
            "me22b214_mlopslib.models.patchnetvlad.tools",
            "me22b214_mlopslib.models.pixloc",
            "me22b214_mlopslib.models.pixloc.localization",
            "me22b214_mlopslib.models.pixloc.pixlib",
            "me22b214_mlopslib.models.pixloc.pixlib.datasets",
            "me22b214_mlopslib.models.pixloc.pixlib.geometry",
            "me22b214_mlopslib.models.pixloc.pixlib.models",
            "me22b214_mlopslib.models.pixloc.pixlib.utils",
            "me22b214_mlopslib.models.pixloc.utils",
            "me22b214_mlopslib.models.pixloc.visualization",
            "me22b214_mlopslib.models.posfeat",
            "me22b214_mlopslib.models.posfeat.losses",
            "me22b214_mlopslib.models.posfeat.networks",
            "me22b214_mlopslib.models.quadtree",
            "me22b214_mlopslib.models.quadtree.config",
            "me22b214_mlopslib.models.quadtree.functions",
            "me22b214_mlopslib.models.quadtree.lightning",
            "me22b214_mlopslib.models.quadtree.loftr",
            "me22b214_mlopslib.models.quadtree.loftr.backbone",
            "me22b214_mlopslib.models.quadtree.loftr.loftr_module",
            "me22b214_mlopslib.models.quadtree.loftr.utils",
            "me22b214_mlopslib.models.quadtree.losses",
            "me22b214_mlopslib.models.quadtree.modules",
            "me22b214_mlopslib.models.quadtree.optimizers",
            "me22b214_mlopslib.models.quadtree.utils",
            "me22b214_mlopslib.models.relf",
            "me22b214_mlopslib.models.relf.reresnet_model",
            "me22b214_mlopslib.models.relf.reresnet_model.models",
            "me22b214_mlopslib.models.relf.reresnet_model.models.backbones",
            "me22b214_mlopslib.models.relf.rewrn_model",
            "me22b214_mlopslib.models.relf.rewrn_model.models",
            "me22b214_mlopslib.models.relf.utils",
            "me22b214_mlopslib.models.roma",
            "me22b214_mlopslib.models.roma.models",
            "me22b214_mlopslib.models.roma.models.model_zoo",
            "me22b214_mlopslib.models.roma.models.transformer",
            "me22b214_mlopslib.models.roma.models.transformer.layers",
            "me22b214_mlopslib.models.roma.utils",
            "me22b214_mlopslib.models.rotation_steerers",
            "me22b214_mlopslib.models.rotation_steerers.matchers",
            "me22b214_mlopslib.models.se2loftr",
            "me22b214_mlopslib.models.se2loftr.config",
            "me22b214_mlopslib.models.se2loftr.loftr",
            "me22b214_mlopslib.models.se2loftr.loftr.backbone",
            "me22b214_mlopslib.models.se2loftr.loftr.loftr_module",
            "me22b214_mlopslib.models.se2loftr.loftr.utils",
            "me22b214_mlopslib.models.sfd2",
            "me22b214_mlopslib.models.superpoint",
            "me22b214_mlopslib.models.vggt",
            "me22b214_mlopslib.models.xfeat",
            "me22b214_mlopslib.pipelines",
            "me22b214_mlopslib.pipelines.imc2023",
            "me22b214_mlopslib.pipelines.imc2024",
            "me22b214_mlopslib.postprocesses",
            "me22b214_mlopslib.preprocesses",
            "me22b214_mlopslib.retrievers",
            "me22b214_mlopslib.shortlists",
            "me22b214_mlopslib.utils",
            "me22b214_mlopslib.utils.imc25",
        ],
        package_dir={
            "me22b214_mlopslib": "..",
            "me22b214_mlopslib.clusterings": "../clusterings",
            "me22b214_mlopslib.features": "../features",
            "me22b214_mlopslib.features._research_only": "../features/_research_only",
            "me22b214_mlopslib.features.gim": "../features/gim",
            "me22b214_mlopslib.features.lightglue": "../features/lightglue",
            "me22b214_mlopslib.global_descriptors": "../global_descriptors",
            "me22b214_mlopslib.localizers": "../localizers",
            "me22b214_mlopslib.matchers": "../matchers",
            "me22b214_mlopslib.matchers._research_only": "../matchers/_research_only",
            "me22b214_mlopslib.models": "../models",
            "me22b214_mlopslib.models._research_only": "../models/_research_only",
            "me22b214_mlopslib.models._research_only.magicleap": "../models/_research_only/magicleap",
            "me22b214_mlopslib.models._research_only.silk": "../models/_research_only/silk",
            "me22b214_mlopslib.models._research_only.silk.backbones": "../models/_research_only/silk/backbones",
            "me22b214_mlopslib.models._research_only.silk.backbones.abstract": "../models/_research_only/silk/backbones/abstract",
            "me22b214_mlopslib.models._research_only.silk.backbones.loftr": "../models/_research_only/silk/backbones/loftr",
            "me22b214_mlopslib.models._research_only.silk.backbones.silk": "../models/_research_only/silk/backbones/silk",
            "me22b214_mlopslib.models._research_only.silk.backbones.superpoint": "../models/_research_only/silk/backbones/superpoint",
            "me22b214_mlopslib.models._research_only.silk.backbones.unet": "../models/_research_only/silk/backbones/unet",
            "me22b214_mlopslib.models._research_only.silk.config": "../models/_research_only/silk/config",
            "me22b214_mlopslib.models._research_only.silk.cv": "../models/_research_only/silk/cv",
            "me22b214_mlopslib.models._research_only.silk.losses": "../models/_research_only/silk/losses",
            "me22b214_mlopslib.models._research_only.silk.losses.info_nce": "../models/_research_only/silk/losses/info_nce",
            "me22b214_mlopslib.models._research_only.silk.matching": "../models/_research_only/silk/matching",
            "me22b214_mlopslib.models._research_only.silk.models": "../models/_research_only/silk/models",
            "me22b214_mlopslib.models._research_only.silk.transforms": "../models/_research_only/silk/transforms",
            "me22b214_mlopslib.models._research_only.silk.transforms.cv": "../models/_research_only/silk/transforms/cv",
            "me22b214_mlopslib.models.adamatcher": "../models/adamatcher",
            "me22b214_mlopslib.models.adamatcher.adamatcher": "../models/adamatcher/adamatcher",
            "me22b214_mlopslib.models.adamatcher.adamatcher.ada_module": "../models/adamatcher/adamatcher/ada_module",
            "me22b214_mlopslib.models.adamatcher.adamatcher.backbone": "../models/adamatcher/adamatcher/backbone",
            "me22b214_mlopslib.models.adamatcher.adamatcher.utils": "../models/adamatcher/adamatcher/utils",
            "me22b214_mlopslib.models.adamatcher.config": "../models/adamatcher/config",
            "me22b214_mlopslib.models.adamatcher.lightning": "../models/adamatcher/lightning",
            "me22b214_mlopslib.models.adamatcher.utils": "../models/adamatcher/utils",
            "me22b214_mlopslib.models.alike": "../models/alike",
            "me22b214_mlopslib.models.aliked": "../models/aliked",
            "me22b214_mlopslib.models.aliked.nets": "../models/aliked/nets",
            "me22b214_mlopslib.models.aspanformer": "../models/aspanformer",
            "me22b214_mlopslib.models.aspanformer.aspanformer": "../models/aspanformer/aspanformer",
            "me22b214_mlopslib.models.aspanformer.aspanformer.aspan_module": "../models/aspanformer/aspanformer/aspan_module",
            "me22b214_mlopslib.models.aspanformer.aspanformer.backbone": "../models/aspanformer/aspanformer/backbone",
            "me22b214_mlopslib.models.aspanformer.aspanformer.utils": "../models/aspanformer/aspanformer/utils",
            "me22b214_mlopslib.models.aspanformer.config": "../models/aspanformer/config",
            "me22b214_mlopslib.models.aspanformer.utils": "../models/aspanformer/utils",
            "me22b214_mlopslib.models.cvnet": "../models/cvnet",
            "me22b214_mlopslib.models.cvnet.core": "../models/cvnet/core",
            "me22b214_mlopslib.models.cvnet.model": "../models/cvnet/model",
            "me22b214_mlopslib.models.cvnet.model.base": "../models/cvnet/model/base",
            "me22b214_mlopslib.models.dac": "../models/dac",
            "me22b214_mlopslib.models.darkfeat": "../models/darkfeat",
            "me22b214_mlopslib.models.delf_pytorch": "../models/delf_pytorch",
            "me22b214_mlopslib.models.dinov2_salad": "../models/dinov2_salad",
            "me22b214_mlopslib.models.dinov2_salad.models": "../models/dinov2_salad/models",
            "me22b214_mlopslib.models.dinov2_salad.models.aggregators": "../models/dinov2_salad/models/aggregators",
            "me22b214_mlopslib.models.dinov2_salad.models.backbones": "../models/dinov2_salad/models/backbones",
            "me22b214_mlopslib.models.dinov2_salad.models.dinov2": "../models/dinov2_salad/models/dinov2",
            "me22b214_mlopslib.models.dinov2_salad.models.dinov2.hub": "../models/dinov2_salad/models/dinov2/hub",
            "me22b214_mlopslib.models.dinov2_salad.models.dinov2.hub.depth": "../models/dinov2_salad/models/dinov2/hub/depth",
            "me22b214_mlopslib.models.dinov2_salad.models.dinov2.layers": "../models/dinov2_salad/models/dinov2/layers",
            "me22b214_mlopslib.models.dinov2_salad.utils": "../models/dinov2_salad/utils",
            "me22b214_mlopslib.models.dirtorch": "../models/dirtorch",
            "me22b214_mlopslib.models.dirtorch.nets": "../models/dirtorch/nets",
            "me22b214_mlopslib.models.dirtorch.nets.backbones": "../models/dirtorch/nets/backbones",
            "me22b214_mlopslib.models.dirtorch.nets.layers": "../models/dirtorch/nets/layers",
            "me22b214_mlopslib.models.dirtorch.utils": "../models/dirtorch/utils",
            "me22b214_mlopslib.models.dkm": "../models/dkm",
            "me22b214_mlopslib.models.dkm.models": "../models/dkm/models",
            "me22b214_mlopslib.models.dkm.models.model_zoo": "../models/dkm/models/model_zoo",
            "me22b214_mlopslib.models.dkm.utils": "../models/dkm/utils",
            "me22b214_mlopslib.models.doppelgangers": "../models/doppelgangers",
            "me22b214_mlopslib.models.doppelgangers.datasets": "../models/doppelgangers/datasets",
            "me22b214_mlopslib.models.doppelgangers.models": "../models/doppelgangers/models",
            "me22b214_mlopslib.models.doppelgangers.third_party": "../models/doppelgangers/third_party",
            "me22b214_mlopslib.models.doppelgangers.third_party.loftr": "../models/doppelgangers/third_party/loftr",
            "me22b214_mlopslib.models.doppelgangers.third_party.loftr.backbone": "../models/doppelgangers/third_party/loftr/backbone",
            "me22b214_mlopslib.models.doppelgangers.third_party.loftr.loftr_module": "../models/doppelgangers/third_party/loftr/loftr_module",
            "me22b214_mlopslib.models.doppelgangers.third_party.loftr.utils": "../models/doppelgangers/third_party/loftr/utils",
            "me22b214_mlopslib.models.doppelgangers.utils": "../models/doppelgangers/utils",
            "me22b214_mlopslib.models.ecotr": "../models/ecotr",
            "me22b214_mlopslib.models.ecotr.config": "../models/ecotr/config",
            "me22b214_mlopslib.models.ecotr.models": "../models/ecotr/models",
            "me22b214_mlopslib.models.ecotr.models.base": "../models/ecotr/models/base",
            "me22b214_mlopslib.models.ecotr.models.ecotr_modules": "../models/ecotr/models/ecotr_modules",
            "me22b214_mlopslib.models.ecotr.models.utils": "../models/ecotr/models/utils",
            "me22b214_mlopslib.models.ecotr.utils": "../models/ecotr/utils",
            "me22b214_mlopslib.models.edgepoint2": "../models/edgepoint2",
            "me22b214_mlopslib.models.efficientloftr": "../models/efficientloftr",
            "me22b214_mlopslib.models.efficientloftr.config": "../models/efficientloftr/config",
            "me22b214_mlopslib.models.efficientloftr.loftr": "../models/efficientloftr/loftr",
            "me22b214_mlopslib.models.efficientloftr.loftr.backbone": "../models/efficientloftr/loftr/backbone",
            "me22b214_mlopslib.models.efficientloftr.loftr.loftr_module": "../models/efficientloftr/loftr/loftr_module",
            "me22b214_mlopslib.models.efficientloftr.loftr.utils": "../models/efficientloftr/loftr/utils",
            "me22b214_mlopslib.models.featurebooster": "../models/featurebooster",
            "me22b214_mlopslib.models.fftformer": "../models/fftformer",
            "me22b214_mlopslib.models.fsnet": "../models/fsnet",
            "me22b214_mlopslib.models.fsnet.modules": "../models/fsnet/modules",
            "me22b214_mlopslib.models.gim": "../models/gim",
            "me22b214_mlopslib.models.gim.dkm": "../models/gim/dkm",
            "me22b214_mlopslib.models.gim.dkm.models": "../models/gim/dkm/models",
            "me22b214_mlopslib.models.gim.dkm.models.model_zoo": "../models/gim/dkm/models/model_zoo",
            "me22b214_mlopslib.models.gim.dkm.utils": "../models/gim/dkm/utils",
            "me22b214_mlopslib.models.gim.gluefactory": "../models/gim/gluefactory",
            "me22b214_mlopslib.models.gim.gluefactory.models": "../models/gim/gluefactory/models",
            "me22b214_mlopslib.models.gim.gluefactory.models.backbones": "../models/gim/gluefactory/models/backbones",
            "me22b214_mlopslib.models.gim.gluefactory.models.extractors": "../models/gim/gluefactory/models/extractors",
            "me22b214_mlopslib.models.gim.gluefactory.models.matchers": "../models/gim/gluefactory/models/matchers",
            "me22b214_mlopslib.models.gim.gluefactory.models.utils": "../models/gim/gluefactory/models/utils",
            "me22b214_mlopslib.models.gim.gluefactory.utils": "../models/gim/gluefactory/utils",
            "me22b214_mlopslib.models.gim.loftr": "../models/gim/loftr",
            "me22b214_mlopslib.models.gim.loftr.backbone": "../models/gim/loftr/backbone",
            "me22b214_mlopslib.models.gim.loftr.configs": "../models/gim/loftr/configs",
            "me22b214_mlopslib.models.gim.loftr.configs.outdoor": "../models/gim/loftr/configs/outdoor",
            "me22b214_mlopslib.models.gim.loftr.submodules": "../models/gim/loftr/submodules",
            "me22b214_mlopslib.models.gim.loftr.utils": "../models/gim/loftr/utils",
            "me22b214_mlopslib.models.grounded_sam": "../models/grounded_sam",
            "me22b214_mlopslib.models.isc": "../models/isc",
            "me22b214_mlopslib.models.lanet": "../models/lanet",
            "me22b214_mlopslib.models.lanet.network_v1": "../models/lanet/network_v1",
            "me22b214_mlopslib.models.mapfree": "../models/mapfree",
            "me22b214_mlopslib.models.mast3r": "../models/mast3r",
            "me22b214_mlopslib.models.matchformer": "../models/matchformer",
            "me22b214_mlopslib.models.matchformer.backbone": "../models/matchformer/backbone",
            "me22b214_mlopslib.models.matchformer.utils": "../models/matchformer/utils",
            "me22b214_mlopslib.models.moge": "../models/moge",
            "me22b214_mlopslib.models.mtldesc": "../models/mtldesc",
            "me22b214_mlopslib.models.mtldesc.vit": "../models/mtldesc/vit",
            "me22b214_mlopslib.models.ncmnet": "../models/ncmnet",
            "me22b214_mlopslib.models.omniglue_onnx": "../models/omniglue_onnx",
            "me22b214_mlopslib.models.omniglue_onnx.dinov2": "../models/omniglue_onnx/dinov2",
            "me22b214_mlopslib.models.openglue": "../models/openglue",
            "me22b214_mlopslib.models.openglue.models": "../models/openglue/models",
            "me22b214_mlopslib.models.openglue.models.features": "../models/openglue/models/features",
            "me22b214_mlopslib.models.openglue.models.features.opencv": "../models/openglue/models/features/opencv",
            "me22b214_mlopslib.models.openglue.models.superglue": "../models/openglue/models/superglue",
            "me22b214_mlopslib.models.openglue.utils": "../models/openglue/utils",
            "me22b214_mlopslib.models.panet": "../models/panet",
            "me22b214_mlopslib.models.patchnetvlad": "../models/patchnetvlad",
            "me22b214_mlopslib.models.patchnetvlad.models": "../models/patchnetvlad/models",
            "me22b214_mlopslib.models.patchnetvlad.tools": "../models/patchnetvlad/tools",
            "me22b214_mlopslib.models.pixloc": "../models/pixloc",
            "me22b214_mlopslib.models.pixloc.localization": "../models/pixloc/localization",
            "me22b214_mlopslib.models.pixloc.pixlib": "../models/pixloc/pixlib",
            "me22b214_mlopslib.models.pixloc.pixlib.datasets": "../models/pixloc/pixlib/datasets",
            "me22b214_mlopslib.models.pixloc.pixlib.geometry": "../models/pixloc/pixlib/geometry",
            "me22b214_mlopslib.models.pixloc.pixlib.models": "../models/pixloc/pixlib/models",
            "me22b214_mlopslib.models.pixloc.pixlib.utils": "../models/pixloc/pixlib/utils",
            "me22b214_mlopslib.models.pixloc.utils": "../models/pixloc/utils",
            "me22b214_mlopslib.models.pixloc.visualization": "../models/pixloc/visualization",
            "me22b214_mlopslib.models.posfeat": "../models/posfeat",
            "me22b214_mlopslib.models.posfeat.losses": "../models/posfeat/losses",
            "me22b214_mlopslib.models.posfeat.networks": "../models/posfeat/networks",
            "me22b214_mlopslib.models.quadtree": "../models/quadtree",
            "me22b214_mlopslib.models.quadtree.config": "../models/quadtree/config",
            "me22b214_mlopslib.models.quadtree.functions": "../models/quadtree/functions",
            "me22b214_mlopslib.models.quadtree.lightning": "../models/quadtree/lightning",
            "me22b214_mlopslib.models.quadtree.loftr": "../models/quadtree/loftr",
            "me22b214_mlopslib.models.quadtree.loftr.backbone": "../models/quadtree/loftr/backbone",
            "me22b214_mlopslib.models.quadtree.loftr.loftr_module": "../models/quadtree/loftr/loftr_module",
            "me22b214_mlopslib.models.quadtree.loftr.utils": "../models/quadtree/loftr/utils",
            "me22b214_mlopslib.models.quadtree.losses": "../models/quadtree/losses",
            "me22b214_mlopslib.models.quadtree.modules": "../models/quadtree/modules",
            "me22b214_mlopslib.models.quadtree.optimizers": "../models/quadtree/optimizers",
            "me22b214_mlopslib.models.quadtree.utils": "../models/quadtree/utils",
            "me22b214_mlopslib.models.relf": "../models/relf",
            "me22b214_mlopslib.models.relf.reresnet_model": "../models/relf/reresnet_model",
            "me22b214_mlopslib.models.relf.reresnet_model.models": "../models/relf/reresnet_model/models",
            "me22b214_mlopslib.models.relf.reresnet_model.models.backbones": "../models/relf/reresnet_model/models/backbones",
            "me22b214_mlopslib.models.relf.rewrn_model": "../models/relf/rewrn_model",
            "me22b214_mlopslib.models.relf.rewrn_model.models": "../models/relf/rewrn_model/models",
            "me22b214_mlopslib.models.relf.utils": "../models/relf/utils",
            "me22b214_mlopslib.models.roma": "../models/roma",
            "me22b214_mlopslib.models.roma.models": "../models/roma/models",
            "me22b214_mlopslib.models.roma.models.model_zoo": "../models/roma/models/model_zoo",
            "me22b214_mlopslib.models.roma.models.transformer": "../models/roma/models/transformer",
            "me22b214_mlopslib.models.roma.models.transformer.layers": "../models/roma/models/transformer/layers",
            "me22b214_mlopslib.models.roma.utils": "../models/roma/utils",
            "me22b214_mlopslib.models.rotation_steerers": "../models/rotation_steerers",
            "me22b214_mlopslib.models.rotation_steerers.matchers": "../models/rotation_steerers/matchers",
            "me22b214_mlopslib.models.se2loftr": "../models/se2loftr",
            "me22b214_mlopslib.models.se2loftr.config": "../models/se2loftr/config",
            "me22b214_mlopslib.models.se2loftr.loftr": "../models/se2loftr/loftr",
            "me22b214_mlopslib.models.se2loftr.loftr.backbone": "../models/se2loftr/loftr/backbone",
            "me22b214_mlopslib.models.se2loftr.loftr.loftr_module": "../models/se2loftr/loftr/loftr_module",
            "me22b214_mlopslib.models.se2loftr.loftr.utils": "../models/se2loftr/loftr/utils",
            "me22b214_mlopslib.models.sfd2": "../models/sfd2",
            "me22b214_mlopslib.models.superpoint": "../models/superpoint",
            "me22b214_mlopslib.models.vggt": "../models/vggt",
            "me22b214_mlopslib.models.xfeat": "../models/xfeat",
            "me22b214_mlopslib.pipelines": "../pipelines",
            "me22b214_mlopslib.pipelines.imc2023": "../pipelines/imc2023",
            "me22b214_mlopslib.pipelines.imc2024": "../pipelines/imc2024",
            "me22b214_mlopslib.postprocesses": "../postprocesses",
            "me22b214_mlopslib.preprocesses": "../preprocesses",
            "me22b214_mlopslib.retrievers": "../retrievers",
            "me22b214_mlopslib.shortlists": "../shortlists",
            "me22b214_mlopslib.utils": "../utils",
            "me22b214_mlopslib.utils.imc25": "../utils/imc25",
        },
    )


if __name__ == "__main__":
    main()
